# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Engineer.ai_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SVProgressHUD'
pod 'Alamofire'
pod 'SDWebImage'


  # Pods for Engineer.ai_Test

end
